# {{=<% %>=}}
apiVersion: templates.krateo.io/v1alpha1
kind: RepoClone
metadata:
  name: <% name %>-repo-clone
  labels:
    deploymentId: <% deploymentId %>
spec:
  owner: mauro
  title: <% name %>
  description: <% description %>
  icon: fa-solid fa-clover
  links:
    - url: https://github.com/<% organizationName %>/<% repositoryName %>
      title: <% organizationName %>/<% repositoryName %>
      icon: "fa-brands fa-git"
  tags:
    - repo
    - clone
    - template
  widgets:
    - title: Base Settings
      properties:
        - title: name
          description: deployment name
          required: true
          key: name
        - title: description
          description: deployment description
          required: false
          key: description
        - title: namespace
          visible: false
          default: krateo-system
          key: namespace
    - title: Repository settings
      properties:
        - title: Repo Name
          description: Repo Name
          required: true
          key: repositoryName
        - title: Organization Name
          description: Organization Name
          required: true
          key: organizationName
        - title: Provider
          description: Provider
          required: true
          key: provider
          default: github
          options:
            - title: Github
              value: github
