apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: template-repo-clone
spec:
  owner: mauro.sala@kiratech.it
  title: Repo Clone
  description: repo clone sample demo
  icon: fa-solid fa-clone
  tags:
    - repo
    - clone
    - template
  widgets:
    - title: Deployment Settings
      properties:
        - title: name
          description: deployment name
          required: true
          key: name
        - title: description
          description: deployment description
          required: false
          key: description
        - title: namespace
          hidden: true
          default: krateo-system
          key: namespace
    - title: Repository settings
      properties:
        - title: Organization Name
          description: Organization Name
          required: true
          key: organizationName
        - title: Repo Name
          description: Repo Name
          required: true
          default: krateoplatformops
          readOnly: true
          key: repositoryName
        - title: Provider
          description: Provider
          required: true
          key: provider
          type: select
          default: github
          options:
            - title: Github
              value: github
